### ISSUE TITLE
프로젝트 재구성 후속작업

### ISSUE THREAD

**Issue by lijm1358** [kCMI113/Grad_proj#2]
## TODO
- [ ] yaml, .env 설정 정리
- [ ] dataset argument도 **kwargs 형태로 넘겨주기
- [ ] `README.md` 작성하기(프로젝트 구조 및 pre-commit 관련 도움말)
- [ ] pre-commit hook 추가
  - [ ]  정적 타입 검사(pyright나 mypy)
  - [ ] snake_case, CamelCase checking 넣기
  - [ ] commit message formatting
- [ ] type hinting 구체화(ex. `torch.Tensor` 대신 `torch.FloatTensor`, `dict` 대신 `Dict[str, List[int]]` 등)
- [ ] 현재 PR에 변경사항 별 변경 이유 적기
- [ ] config validation 추가
- [ ] discord hook
- [ ] 모델 checkpoint 및 yaml 저장
- [ ] setting file path as argument
- [ ] config.yaml에 negative sampling 비활성화 넣기
- [ ] model에 unused kwargs warning 넣기
- [ ] (가능하면) negative sampling 코드 최적화
- [ ] (가능하면) dataset return 값 개수 줄이기

**Comment by lijm1358** [comment]
#9 으로 대신함
