### ISSUE TITLE
[refactor] models.py 리팩토링

### ISSUE THREAD

**Issue by kCMI113** [kCMI113/Grad_proj#3]
### TODO
---
- [x] 사용하지 않는 옵션 제거
- [x] HF 사용 모델 제거
- [x] 모달 임베딩 데이터셋으로 이동
- [x] 모듈화
